### ISSUE TITLE
팀별 주제 선정

### ISSUE THREAD

**Issue by sidoda** [ossTeamPR/mini_project#2]
CAFE 디저트 자판기
출퇴근 관리 시스템
스터디 카페! 이젠 어디서든 예약할 수 있어요
가계부 프로그램
이외에도 좋은 아이디어 있으면 말씀해주세요

**Comment by HGU-Jeremy** [comment]
저는 CAFE 디저트 자판기가 괜찮아 보이네요

**Comment by sidoda** [comment]
좋습니다
