### ISSUE TITLE
WIKI 내용 분담

### ISSUE THREAD

**Issue by HGU-Jeremy** [ossTeamPR/mini_project#5]
저희 wiki 작성할 내용도 분담해봐요!
어떤 내용이 필요할까요?

**Comment by sidoda** [comment]
서비스
+ 프로그램 소개
+ 기술 상세

디자인
+ 리소스

협업
+ 개발일지
+ 참여자

정도면 괜찮을 것 같아요

**Comment by HGU-Jeremy** [comment]
그럼 페이지나 사이드바는 차차 추가하고
WIKI를 당장 작성해야 하니까
main 페이지에 목차 정도만 적어야겠어요
