### ISSUE TITLE
README.md 역할분담

### ISSUE THREAD

**Issue by HGU-Jeremy** [ossTeamPR/mini_project#6]
팀원이 적절하게 나누어서 작성후 모아서 각자 README.md 파일에 작성)

mini project 주제

mini project 에 대한 소개

image(pixabay 등 무료 이미지 활용)

mini project 가 가지고 있는 대략적인 기능 설명

개발환경 및 언어

팀소개 및 팀원이 맡은 역할

본인이 어떤파트 쓸건지도 정합시다

**Comment by sidoda** [comment]
프로젝트의 기능 설명
개발환경 및 언어
팀소개 하겠습니다

**Comment by HGU-Jeremy** [comment]
프로젝트 주제
프로젝트 소개
이미지 하겠습니다
